version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Gu20ru03
      MYSQL_DATABASE: mydatabase
      MYSQL_USER:  Guru
      MYSQL_PASSWORD: rootpassword
    ports:
      -  "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8001:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data: